### ISSUE TITLE
add a scroll bar horizontally in code output

### ISSUE THREAD

**Issue by cderv** [yihui/rmarkdown-cookbook#111]
Modifying the `pre` tag with css can help achieve that
```css
pre {
  overflow-x: auto;
}
pre code {
  word-wrap: normal;
  white-space: pre;
}
```
part of #38 customization 

## Related SO question

* https://stackoverflow.com/questions/36845178/width-of-r-code-chunk-output-in-rmarkdown-files-knitr-ed-to-html
* https://stackoverflow.com/questions/15385696/adjust-the-output-width-of-r-markdown-html-output
