### ISSUE TITLE
How to prepare a Rmd to send as body in email ? 

### ISSUE THREAD

**Issue by cderv** [yihui/rmarkdown-cookbook#22]
Basically, this use case show how to deactivate all theme and other stuff for nice rendering of html and use a custom css dedicated to email (like https://foundation.zurb.com/emails.html)
````
output: 
  html_document: 
    self_contained: no
    theme: null
    highlight: null
    mathjax: null
    css: ink.css
```` 

The advice seems to use also inline CSS. There is a {juicer} R 📦 that can be useful here. 

I find this question really interesting to show the power of customization one have with Rmarkdown. Rmarkdown is great with all the default to get quick and beautiful result but you can use all the Rmarkdown power to get more custom output dedicated to some specific output like emails

## Related SO questions
* https://stackoverflow.com/questions/34230391/how-to-send-r-markdown-report-in-body-of-email
