### ISSUE TITLE
How to use boostrap predifined classes ? 

### ISSUE THREAD

**Issue by cderv** [yihui/rmarkdown-cookbook#312]
Bootstrap has some predifined classes like 

```css
.hidden {
  display: none !important;
}
```

that can be used directly using Fenced divs

Example based on  #310

````markdown
---
title: "Untitled"
date: "`r Sys.Date()`"
output: html_document
---

::: {.hidden}
$$
\newcommand{\var}{\mathrm{Var}}
$$
:::


Let us test $\var$
````
